version: '3'

services:

  flask-sgx:
    image: ole-hansen/flask-sgx
    container_name: flask-sgx
    build: https://github.com/ole-hansen/docker-flask-sgx.git#main
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
    entrypoint: /app/entrypoint.sh
    command: tail -f /dev/null
  flask-vanilla:
    image: ole-hansen/flask-vanilla
    container_name: flask-vanilla
    build: https://github.com/ole-hansen/docker-flask-sgx.git#demo