version: '3'

services:

  flask-sgx:
    image: enclaive/flask-sgx
    container_name: flask-sgx
    build: https://github.com/enclaive/enclaive-docker-flask-sgx.git#main
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
  flask-vanilla:
    image: enclaive/flask-vanilla
    container_name: flask-vanilla
    build: https://github.com/enclaive/enclaive-docker-flask-sgx.git#demo